version: 2.1
commands:
  save_cache_zstd:
    parameters:
      paths:
        description: 'List of directories which should be added to the cache'
        type: string
        default: '"."'
      key:
        description: 'Unique identifier for this cache'
        type: string
      displayName:
        description: 'Title of the step to be shown in the CircleCI UI'
        type: string
        default: 'Saving Cache'
      when:
        description: 'Specify when to enable or disable the step. Takes the following values: always, on_success, on_fail (default: on_success)'
        type: string
        default: 'on_success'
    steps:
      - run:
          name: << parameters.displayName >>
          when: << parameters.when >>
          command: |
            #!/bin/bash
            KEY=<< parameters.key >>
            echo "Uploading << parameters.paths >> to $KEY"
            set -e
            start=$(date +%s)
            tar -cP << parameters.paths >> |
              zstd -2 --long --threads=4 - |
              rclone rcat \
                --buffer-size=16Mi \
                --checkers=16 \
                --fast-list \
                --ignore-checksum \
                --streaming-upload-cutoff=100Ki \
                --transfers=40 \
                --use-mmap \
                "cache:fast-cache/$KEY.tar.zstd"
            end=$(date +%s)
            runtime=$((end - start))
            echo "Upload: $runtime seconds"
            echo "cache:fast-cache/$KEY.tar.zstd"

jobs:
  zstd:
    resource_class: 'small'
    # working_directory: /mnt/ramdisk
    docker:
      - image: node:18-slim
    steps:
      - run: apt-get update && apt-get install -y git openssh-client
      - checkout
      - restore_cache:
          keys:
            - v1-
      - run: apt-get install -y tar zstd rclone
      - run: rclone config create cache "google cloud storage" location=us-east1 bucket_policy_only=true env_auth=true
      - save_cache_zstd:
          key: v1-$CIRCLE_SHA1<< pipeline.git.revision >>
          paths: 'node_modules/'
  circleci:
    resource_class: 'arm.large'
    # working_directory: /mnt/ramdisk
    docker:
      - image: node:18-slim
    steps:
      - run: npm install pnpm -g
      - run: apt-get update && apt-get install -y git openssh-client
      - checkout
      - run: pnpm install
      - run: pnpm install --ignore-scripts bloater
      # - run: pnpm run start:createData
      - save_cache:
          key: v1-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - node_modules/
      - run: mv node_modules uploads.old
      - restore_cache:
          keys:
            - v1-

workflows:
  comparison:
    jobs:
      # - zstd:
      #     requires:
      #       - circleci
      - zstd
      # - circleci
