version: 2.1

jobs:
  zstd:
    resource_class: 'arm.large'
    # working_directory: /mnt/ramdisk
    # parallelism: 1
    docker:
      - image: node:18-slim
    steps:
      - run: npm install pnpm -g
      - run: apt-get update && apt-get install -y curl git openssh-client mbuffer tar zstd lz4 rclone
      - run: rclone config create cache "google cloud storage" location=us-east1 bucket_policy_only=true env_auth=true
      - checkout
      - run: pnpm install
      - run: pnpm install --ignore-scripts bloater
      # - run: pnpm run start:createData
      - run: pnpm run start:upload-zstd
      - run: pnpm run start:restore-zstd
  lz4:
    resource_class: 'arm.large'
    # working_directory: /mnt/ramdisk
    # parallelism: 1
    docker:
      - image: node:18-slim
    steps:
      - run: npm install pnpm -g
      - run: apt-get update && apt-get install -y curl git openssh-client mbuffer tar zstd lz4 rclone
      - run: rclone config create cache "google cloud storage" location=us-east1 bucket_policy_only=true env_auth=true
      - checkout
      - run: pnpm install
      - run: pnpm install --ignore-scripts bloater
      # - run: pnpm run start:createData
      - run: pnpm run start:upload-lz4
      - run: pnpm run start:restore-lz4
  circleci:
    resource_class: 'arm.large'
    # working_directory: /mnt/ramdisk
    # parallelism: 1
    docker:
      - image: node:18-slim
    steps:
      - run: npm install pnpm -g
      - checkout
      - run: pnpm install
      - run: pnpm install --ignore-scripts bloater
      # - run: pnpm run start:createData
      - save_cache:
          key: v1-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.CIRCLE_SHA1 }}-{{ .Environment.CIRCLE_NODE_INDEX }}
          paths:
            - node_modules/
      - run: mv node_modules uploads.old
      - restore_cache:
          keys:
            - v1-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.CIRCLE_SHA1 }}-{{ .Environment.CIRCLE_NODE_INDEX }}

workflows:
  comparison:
    jobs:
      - lz4
      - zstd:
          requires:
            - lz4
      - circleci:
          requires:
            - zstd