version: 2.1
commands:
  save_cache_zstd:
    parameters:
      paths:
        description: 'List of directories which should be added to the cache'
        type: string
        default: '"/tmp" "node_modules/"'
      cacheKey:
        description: 'Unique identifier for this cache'
        type: string
        default: 'v1-{{ .Environment.CIRCLE_SHA1 }}'
      displayName:
        description: 'Title of the step to be shown in the CircleCI UI'
        type: string
        default: 'Saving Cache'
      when:
        description: 'Specify when to enable or disable the step. Takes the following values: always, on_success, on_fail (default: on_success)'
        type: string
        default: 'on_success'
    steps:
      - run:
          name: << parameters.displayName >>
          when: << parameters.when >>
          command: pnpm run start:upload-zstd -- "{{ .parameters.cacheKey}}" "{{ .parameters.paths}}"

jobs:
  zstd:
    resource_class: 'small'
    # working_directory: /mnt/ramdisk
    docker:
      - image: node:18-slim
    steps:
      - run: apt-get update && apt-get install -y git openssh-client
      - checkout
      - restore_cache:
          keys:
            - v1-
      - run: apt-get install -y tar zstd rclone
      - run: rclone config create cache "google cloud storage" location=us-east1 bucket_policy_only=true env_auth=true
      - save_cache_zstd
      # - save_cache_zstd:
      #     key: v1-{{ .Environment.CIRCLE_SHA1 }}
      #     paths: 'node_modules/'
  circleci:
    resource_class: 'arm.large'
    # working_directory: /mnt/ramdisk
    docker:
      - image: node:18-slim
    steps:
      - run: npm install pnpm -g
      - run: apt-get update && apt-get install -y git openssh-client
      - checkout
      - run: pnpm install
      - run: pnpm install --ignore-scripts bloater
      # - run: pnpm run start:createData
      - save_cache:
          key: v1-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - node_modules/
      - run: mv node_modules uploads.old
      - restore_cache:
          keys:
            - v1-

workflows:
  comparison:
    jobs:
      # - zstd:
      #     requires:
      #       - circleci
      - zstd
      - circleci
