version: 2.1

jobs:
  zstd:
    resource_class: 'arm.large'
    # working_directory: /mnt/ramdisk
    # parallelism: 1
    parameters:
      speed:
        type: string
      long:
        type: string
      threads:
        type: string
    docker:
      - image: node:18-slim
    environment:
      THREADS: << parameters.threads >>
      LONG: << parameters.long >>
      SPEED: << parameters.speed >>
    steps:
      - run: npm install pnpm -g
      - run: apt-get update && apt-get install -y curl git openssh-client mbuffer tar zstd lz4 rclone
      - run: rclone config create cache "google cloud storage" location=us-east1 bucket_policy_only=true env_auth=true
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.CIRCLE_SHA1 }}-{{ .Environment.CIRCLE_NODE_INDEX }}
      # - run: pnpm install
      # - run: pnpm install --ignore-scripts bloater
      # - run: pnpm run start:createData
      - run: pnpm run start:upload-zstd
      - run: pnpm run start:restore-zstd
  circleci:
    resource_class: 'arm.large'
    # working_directory: /mnt/ramdisk
    # parallelism: 1
    docker:
      - image: node:18-slim
    steps:
      - run: npm install pnpm -g
      - run: apt-get update && apt-get install -y curl git openssh-client mbuffer tar zstd lz4 rclone
      - checkout
      - run: pnpm install
      - run: pnpm install --ignore-scripts bloater
      # - run: pnpm run start:createData
      - save_cache:
          key: v1-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.CIRCLE_SHA1 }}-{{ .Environment.CIRCLE_NODE_INDEX }}
          paths:
            - node_modules/
      - run: mv node_modules uploads.old
      - restore_cache:
          keys:
            - v1-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.CIRCLE_SHA1 }}-{{ .Environment.CIRCLE_NODE_INDEX }}

workflows:
  comparison:
    jobs:
      - zstd:
          requires:
            - circleci
          matrix:
            parameters:
              threads:
                - "--threads=0"
                - "--threads=1"
              long:
                - "--long"
                - ""
              speed:
                - "--fast=5"
                - "--fast=4"
                - "--fast=3"
                - "--fast=2"
                - "--fast=1"
                - "--fast=0"
                - "--adapt"
                - "-1"
                - "-2"
                - "-3"
                - "-4"
                - "-5"
                - "-6"
                - "-7"
                - "-8"
                - "-9"
                - "-10"
                - "-11"
                - "-12"
                - "-13"
                - "-14"
                - "-15"
                - "-16"
                - "-17"
                - "-18"
                - "-19"
                - "--ultra -20"
                - "--ultra -21"
                - "--ultra -22"
      - circleci
