version: 2.1

jobs:
  zstd:
    resource_class: large
    working_directory: /mnt/ramdisk
    docker:
      - image: node:18-slim
    steps:
      - run: npm install pnpm -g
      - run: apt-get update && apt-get install -y curl tar zstd rclone
      - run: rclone config create cache b2 account=$B2_ACCOUNT_ID key=$B2_APPLICATION_KEY bucket=fast-cache upload_cutoff=5M chunk_size=5M disable_checksum=true hard_delete=true memory_pool_use_mmap=true
      - checkout
      - run: pnpm install
      - run: pnpm run start:createData
      - run: pnpm run start:upload
      - run: pnpm run start:restore
  circleci:
    resource_class: large
    working_directory: /mnt/ramdisk
    docker:
      - image: node:18-slim
    steps:
      - run: npm install pnpm -g
      - checkout
      - run: pnpm install
      - run: pnpm run start:createData
      - save_cache:
          key: v1-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - node_modules/uploads/
      - run: mv node_modules/uploads uploads.old
      - restore_cache:
          keys:
            - v1-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.CIRCLE_SHA1 }}

workflows:
  comparison:
    jobs:
      - zstd
      # - circleci
      # - circleci:
      #     requires:
      #       - zstd
